theme: jekyll-theme-slate
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>O nama</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

	<link rel="stylesheet" href="assets/css/animate.css" rel="stylesheet">
	<link rel="stylesheet" href="assets/css/nexus.css" rel="stylesheet">
	
</head>

<body>

    <div class="brand">Glotz d.o.o</div>
    

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="Naslovnica.html">Glotz d.o.o</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
			
			
			
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		
                <ul class="nav navbar-nav">
                    <li>
                        <b><a href="Naslovnica.html">Naslovnica</a></b>
                    </li>
                    <li>
                       <b> <a href="O nama.html">O nama</a></b>
                    </li>
					
					<li>
                       <b> <a href="Adaptacija.html">Adaptacija</a></b>
                    </li>
					
					<li>
                       <b> <a href="TAPISERIJE.html">Tapiserije</a></b>
                    </li>
					
					<li>
                       <b> <a href="KERAMIKA I SANITARIJE.html">Keramika i sanitarije</a></b>
                    </li>
					
					<li>
                       <b> <a href="Kontakt.html">Kontakt</a></b>
                    </li>	
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">

        <div class="row">
            <div class="box">
                <!--<div class="col-lg-12">
                    <hr>
                    <h1 class="intro-text text-center">
                        <dfm>Glotz d.o.o</dfm>
                    </h1>
                    <hr>
                </div>-->
               
                <div class="col-md-6">
                   
				<p>Firma Glotz d.o.o sa sjedištem u Splitu bavi se završnim radovima u graditeljstvu.</p>
<p>Nakon višegodišnjeg iskustva u inozemstvu, odlučili smo taj standard i kvalitetu prenijeti i u Hrvatsku.</p>
<p>Visoka očekivanja poznatih klijenata uspjevamo zadovoljiti zahvaljujući znanju,iskustvu, inventivnosti i kreativnosti.</p>
<p>Zadovoljstvo nam je kada naši klijenti imaju jasnu viziju svog doma.<p><p> Budući da je naš cilj da im to i omogućimo, osmislili smo uslugu besplatnog savjetovanja kako bi klijenti izbjegli neugodna iznenađenja i nepotrebne troškove. </p>
<p>Nesto</p>

<h2>USLUGE KOJE NUDIMO:</h2>
			
		<ul>
                    <li>
                        <b><a href="#">„KLJUČ U  RUKE“</b> - adaptacija ili renoviranje objekta do spremnosti za useljenje</a>
                    </li>
					
					<li>
                        <b><a href="#">ZIDARSKI RADOVI</b> -  pregradni zidovi</a>
                    </li>
					
					<li>
                        <b><a href="#">KERAMIKA I SANITARIJE</a></b>
                    </li>
					
					<li>
                        <b><a href="#">ELEKTRO I VODOINSTALACIJE</a></b>
                    </li>
					
					<li>
                        <b><a href="#">PODOPOLAGAČKI RADOVI</b> -parket, laminat, pločice</a>
                    </li>
					
					<li>
                        <b><a href="#">SOBOSLIKARSKI RADOVI</a></b>
                    </li>
					
					<li>
                        <b><a href="#">ZIDNE TAPETE</b> - sve vrste klasičnih kao i fototapete na papiru, staklu, pleksiglasu</a>
                    </li>
				</ul>
			   </div>
                <div class="clearfix"></div>
            </div>
        </div>

       

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>
